### ISSUE TITLE
On mobile, user page scroll buttons make it jump back and forth

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver.Website#119]
![out](https://user-images.githubusercontent.com/1794388/84872363-7994ed00-b08a-11ea-9205-3a17241ea7ff.gif)

**Comment by AiAe** [comment]
Cannot replicate or test. (Desktop FF wont work either for replicating)
If someone else has Android device and uses Firefox and knows css/js please look into trying to fix those.
