### ISSUE TITLE
Search ends up partially off-screen on ff preview

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver.Website#134]
![Screenshot_20200628-082712](https://user-images.githubusercontent.com/1794388/85938827-4cadc900-b919-11ea-9b58-e3c21676a4dd.jpg)

**Comment by AiAe** [comment]
Cannot replicate or test. (Desktop FF wont work either for replicating)
If someone else has Android device and uses Firefox and knows css/js please look into trying to fix those.
