### ISSUE TITLE
Account role should be centered, and there should be spacing between these details on mobile

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver.Website#149]
![image](https://user-images.githubusercontent.com/25614516/86274685-10d86500-bba0-11ea-98e0-d944f70f0e95.png) 

Looking at moderator, you can see it's shifted to the left, this would look much better being centered (perhaps along with online status). Also space them out a bit as it looks too crammed.

**Comment by AiAe** [comment]
What browser do you use? Its centered on Chrome
![https://i.kys.ovh/V0f5.png](https://i.kys.ovh/V0f5.png)

**Comment by Reyder95** [comment]
Chrome as well. I was using dev tools though.

**Comment by Reyder95** [comment]
Actually I used it on normal chrome on my phone and same thing.
