### ISSUE TITLE
Tablet profile navigation not centered

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver.Website#150]
![image](https://user-images.githubusercontent.com/25614516/86274942-7fb5be00-bba0-11ea-9ff1-572064cb8e25.png)

Would look much better if this was centered.

**Comment by AiAe** [comment]
What browser do you use? Its centered on Chrome
![https://i.kys.ovh/V0f5.png](https://i.kys.ovh/V0f5.png)

**Comment by AiAe** [comment]
Its not possible to center it, because its draggable on smaller devices.
