### ISSUE TITLE
Links dont work in "about me"

### ISSUE THREAD

**Issue by llAnasll** [Quaver/Quaver.Website#156]
![Screenshot_153](https://user-images.githubusercontent.com/46055365/86305294-96e0c400-bc11-11ea-8b86-61c88f574acd.png)

**Comment by Reyder95** [comment]
It's bbcode (and html). You have to type
![image](https://user-images.githubusercontent.com/25614516/86307268-53239580-bbe4-11ea-9d13-821069c99947.png)

For example. <a href="https://quavergame.com">Hi this is quavergame</a> is 
![image](https://user-images.githubusercontent.com/25614516/86307300-6c2c4680-bbe4-11ea-8274-7be6cc2ffe22.png)
