### ISSUE TITLE
Quaver logo jumps around when you click the gear on mobile

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver.Website#163]
https://cdn.discordapp.com/attachments/173095830205628417/728712948645888040/20-07-03-23-41-32.mp4

**Comment by AiAe** [comment]
Issue connected with https://github.com/Quaver/Quaver.Website/issues/35

**Comment by AiAe** [comment]
Cannot replicate or test. (Desktop FF wont work either for replicating)
If someone else has Android device and uses Firefox and knows css/js please look into trying to fix those.
