### ISSUE TITLE
Team page should have smaller avatars on mobile

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver.Website#166]
![Screenshot_20200703-235049](https://user-images.githubusercontent.com/1794388/86496931-1e504380-bd88-11ea-866f-4f8da8d3aedb.jpg)
This should have 2 or 3 people per row

**Comment by AiAe** [comment]
Won't do 2 or 3 per row but will lower the avatar size.

**Comment by YaLTeR** [comment]
wdym there's a ton of space there to make it at least 2 per row
