### ISSUE TITLE
"About Me" panel improvements

### ISSUE THREAD

**Issue by Janko5** [Quaver/Quaver.Website#169]
There are several things that would make creating a description "About me" easier:
- preview button
- buttons with BBCodes (for example like in github) ![image](http://puu.sh/G3n96/d8a49c0618.png)
- edit button in top right on profile page like in osu ![image](http://puu.sh/G3nbL/ee16c6b3e6.png)

**Comment by AiAe** [comment]
Everything but preview is added. Will wait for module update due to issues.

**Comment by AiAe** [comment]
Preview won't be added.
