### ISSUE TITLE
Markdown and HTML usage very limited/broken for the description for a map

### ISSUE THREAD

**Issue by lilxleb** [Quaver/Quaver.Website#188]
Tried
1. Adding a video to the description, didnt work, only showed a frame, no video
2. Using h1 and h2, i think those are disabled because of the title of the map
3. Adding images, did not work
4. Moving the text around using `[center]` `<center>` and so on for the other sides, neither syntax worked.

In my opinion, this is a hinderance to the ability that the mapper can be creative to. Having a good description is a good way to draw in more players to your song, especially when clicking on the download link.

**Comment by AiAe** [comment]
Mapset descriptions only Markdown is allowed, we didn't move to BBCode because we used it since the beginning.
About Header tags I will look into it once I have time.
