### ISSUE TITLE
Feature Request: Add percentile ranking on stats page

### ISSUE THREAD

**Issue by prank855** [Quaver/Quaver.Website#194]
Can help give better info on just how much better or worse you are against the general player base. Being top 100 is cool, but not if there's only 200 players total in the game, which only makes you top 50% of all players, as an example.

**Comment by IceDynamix** [comment]
While it isn't a direct solution, you can easily check your percentile by comparing your rank with the number of registered players, which is visible on the [Quaver Website](https://quavergame.com/) on the right side. Current number of registered players is around 16000, so top 100 would be top 0.625%.

**Comment by Adrriii** [comment]
On osudaily I put this feature but it's probably better to count the number of players by counting the rank of a player who already has some rating (I used 50 pp for osu, could be like 5 QR for quaver)
