### ISSUE TITLE
Adding warning icon when someone tried to mod with multiple timestamp

### ISSUE THREAD

**Issue by Zephyr3755** [Quaver/Quaver.Website#197]
Add [https://puu.sh/G71T1.jpg](url) icon or equivalent after **Submit** button, or a pop up message after a person failed submitting the mod instead of showing error like [https://puu.sh/G71SA.png](url)

**Comment by AiAe** [comment]
If you want to use multiple timestamps you can write it as a comment and it will be still a link to editor.
Example:
```
`234873284|1,234234|2,23423|3`
```

**Comment by Zephyr3755** [comment]
i actually tried it, here's the original timestamp https://quavergame.com/mapset/map/14127/mods#mod_749
