### ISSUE TITLE
Feature request: Encouraging better spread through ranking queue 'priority'

### ISSUE THREAD

**Issue by Vmbivalence** [Quaver/Quaver.Website#204]
I was told to post this here, so here's my idea. 

Quaver seems to be currently suffering of a bit of a lack of lower difficulties, I believe it's especially painful in 7k maps. Ranking criteria only force 2 difficulties to have a spread and that only goes for maps less than 2:30 in map time. It doesn't encourage more full spread at all, leaving many new players a bit in the dry, I'd even argue it discourages new players from starting with Quaver. osu! for instance solves this issue by just brutally enforcing a complete spread, but this has its own issues. For one, it's tiring to the mapper. Making 5 or 6 difficulties, most of which aren't interesting at all is not the most fun exercise. Additionally, certain songs, such as Doppelganger have top difficulties with ridiculously high difficulty and density, while they still need an Easy or Normal to be rankable. This makes these charts so incredibly watered down, barely following the song just to be easy enough for the ranking criteria and BNs to have mercy. 

My idea does something in between osu! and Quaver, in a way. Quaver currently uses just a list of maps submitted for rank, Ranking Supervisors go through them one by one, more or less in order. That's perfectly fine on its own, but there's a slight modification that would encourage mappers to create more full spreads. It's possible to have charts with a better spread OR marathon maps (I suggest 4+ minutes in length) appear higher up on the list, potentially skipping a lot of the wait time (though of course, not a lot, I wouldn't suggest skipping more than half). This doesn't force anyone to have a full spread, but definitely encourages the mapper to spend a bit more time to potentially saved it later on, waiting less, while giving newer players a bit more stuff to enjoy. Now, what is a better spread, in my opinion? What a better spread for a given map is would depend, I imagine, mostly on the top difficulty's Difficulty Rating (referred to as DR from now on). A good spread would be a spread, where at least some difficulties can be fit into a more or less regular pattern of difficulty increase. It's hard to pinpoint what that increase would be, but perhaps something like 4-6 DR, with +-1 window for more leniency, as of course it makes no sense to fine tune that stuff perfectly. Additionally, DR would determine what the lowest difficulty (or rather, DR of the lowest difficulty) can be, again with some leniency. Why that choice? There's no need to have an easy difficulty for Blastix Riotz or similar, the oversimplification gets quite ridiculous. It's hard to suggest numbers, but I'd say Blastix Riotz doesn't need anything below Insane. Better spread is probably also at least 4 difficulties, unless the top difficulty is too low, there's no need to cram 4 difficulties into 0-2 DR space, just tedious for the mapper. Perhaps up to 5 difficulties in the case of high DR stuff, but I think that 4 should be more or less good enough.  

Important to note, is that maps that already meet the requirements for good spread do not get any additional bonus for cramming more difficulties in, or going all the way down to Easy on their Doppelganger. I do not want to encourage people making 10 difficulties where 7 are made in 5 minutes each. Also, as mentioned before, marathons (that I suggest be 4 minutes+) are also getting the same boost as 'better spread'. 

This method also doesn't promote anything to the player. It doesn't make it more likely for a player to see charts with better spread / with easier difficulties, it simply lets the map be ranked quicker and more efficiently. Nothing on the player end. This method is just a gentle push toward making the entire game more accessible to people of a broader range of skill, while simultaneously not forcing the mapper into hours of work on 7 difficulties. It doesn't force any ridiculous undermapping, and even discourages it, since the wait time does not get further decreased.  

The problem that this solution creates, however, is development. This system almost certainly requires an automated system to properly place things on the list. That itself isn't that much of an issue, however how things without the boost are treated is a little more difficult to manage. Something like a 'score' system instead of just position in queue based on time, perhaps. Programming it so that things without proper spread still definitely get forward on the list, even if stuff with boost is added ahead of them, so that maps aren’t just stuck at the end for months. I imagine it'd be quite difficult to fine tune, along with the requirements for amount of difficulty, proper DR spread, etc. however I believe it's a worthwhile endeavour. 

Thank you for reading all the way through, I hope you like that idea.

**Comment by AiAe** [comment]
Old outdated
