### ISSUE TITLE
Back after adding friend brings you back to the player page with "add friend" button

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver.Website#208]

**Comment by AiAe** [comment]
I can't replicate this problem

**Comment by YaLTeR** [comment]
![out](https://user-images.githubusercontent.com/1794388/88455897-0e58ea80-ce82-11ea-89a0-535d91418646.gif)

**Comment by AiAe** [comment]
Still can't replicate on Chrome or Firefox on local and live version as well

**Comment by AiAe** [comment]
Will be fixed with https://github.com/Quaver/Quaver.Website/issues/160

**Comment by AiAe** [comment]
It was not fixed with #160
