### ISSUE TITLE
Getting "Approaching The Blue Zenith" Rank Even im still upper 800 Rank

### ISSUE THREAD

**Issue by Kotaruuu** [Quaver/Quaver.Website#246]
![image](https://user-images.githubusercontent.com/70578576/91843044-a61ed500-ec87-11ea-8d5a-4a2ef6092c17.png)
![image](https://user-images.githubusercontent.com/70578576/91843087-b3d45a80-ec87-11ea-8e23-ac3692a528d1.png)

Ive got this by playing Suki! Yuki! Maji Magic 1.65x (speed)

**Comment by AiAe** [comment]
The issue should be resolved, we cannot remove the Steam achievement.
