### ISSUE TITLE
Cant delete a map if its denied for rank

### ISSUE THREAD

**Issue by llAnasll** [Quaver/Quaver.Website#248]
![image](https://user-images.githubusercontent.com/46055365/92492985-4af36200-f1f4-11ea-9fce-6d114224fcf7.png)

**Comment by Razorflamekun** [comment]
I'm 100% positive this is intentional, as per the message you get from when a Ranking Supervisor denies your map.  They expect you to improve upon the map and then resubmit it for rank.

**Comment by robby250** [comment]
lol you shouldnt be so positive if youre not sure, they dont expect anything from you thats just a template message telling you to resubmit for rank if you want, you should be able to delete your map if you want to delete it pretty sure its a bug

**Comment by Razorflamekun** [comment]
Maybe the bug isn't in that, but more so the fact that there should be an option to remove it from the denied status and put it back into an unranked status to where it isn't submitted for rank and isn't denied.  That would probably be the better solution to this issue.

**Comment by AiAe** [comment]
The reason why Delete button is gone is due to people delete their mapsets and want them back afterwards and I strongly suggest to just replace it with another mapset if needed since we limit how many mapsets players can upload.
