### ISSUE TITLE
Squirrel emoji in mapset description results in Cloudflare error

### ISSUE THREAD

**Issue by ph03n1xm** [Quaver/Quaver.Website#266]
When pasting this escaped emoji (🐿️) into a mapset's description, a Cloudflare timeout error occurs after a long wait. This may occur with other unusual characters, but this is untested.

You can reproduce this by doing just that: Paste that emoji into a mapset's description, a mapset you own. Note that it will take a long while for the error to pop up, due to it being a timeout error.

![image](https://user-images.githubusercontent.com/69484229/97945574-8f5f3200-1d4d-11eb-9e55-747cb5751562.png) < The text I used

![image](https://user-images.githubusercontent.com/69484229/97945727-f5e45000-1d4d-11eb-8e3e-024eb14d8a5a.png) < The Cloudflare error (Note that the error occurs within the host)

A couple solutions I see is that you could either check for foreign characters, and reject the description if it has one, or add support for the foreign characters. But hey, I'm not a web developer, so these are just suggestions.

If it helps, this is the mapset that was being used to test this issue. https://quavergame.com/mapset/3838

**Comment by AiAe** [comment]
From what I know this is most likely a server side error, due to our database not allowing the saving of emojis as of now. 
Will look into it in the feature :)
