### ISSUE TITLE
[Suggestion] Remove the ability for users other than the creator/RSes to be able to reply to mods left by other users

### ISSUE THREAD

**Issue by Razorflamekun** [Quaver/Quaver.Website#274]
I don't see why users other than the creator and/or RSes to be able to reply to mods left by users.  In my opinion, only the user that left the mod and the creator of the map should be able to reply to said mod, in addition to other RSes.

**Comment by Janko5** [comment]
> why users other than the creator and/or RSes to be able to reply to mods left by users

For example, to express your opinion if the mod is good/correct, or not and possibly to discuss about the proposed change

**Comment by Razorflamekun** [comment]
> > why users other than the creator and/or RSes to be able to reply to mods left by users
> 
> For example, to express your opinion if the mod is good/correct, or not and possibly to discuss about the proposed change

I guess that makes sense, but that seems to me more something an RS would do instead of a regular user.

**Comment by Razorflamekun** [comment]
That makes sense.  Sorry to bother you with this issue.
