### ISSUE TITLE
Maps Tab Dropdown in Wiki Page is missing.

### ISSUE THREAD

**Issue by chirijidev** [Quaver/Quaver.Website#293]
this is the wiki page
![image](https://user-images.githubusercontent.com/55966752/110464621-4dd10000-810e-11eb-9e7d-2ce45f51747e.png)

this is everything else, i guess
![image](https://user-images.githubusercontent.com/55966752/110466887-465f2600-8111-11eb-967b-bdb97bb23cc9.png)

**Comment by AiAe** [comment]
Fixed
