### ISSUE TITLE
[Feature Request] Add "Copied!" on User Profiles

### ISSUE THREAD

**Issue by PcTechery** [Quaver/Quaver.Website#296]
So I noticed that you got this:

![image](https://user-images.githubusercontent.com/32001480/111482110-f7655200-8709-11eb-8108-c25e51e5dc73.png)
It gets the things done and all but I feel like when you click it and it actually copies **the bubble should turn green and says "Copied!" for 3 seconds, and then turns back to normal.** I feel this would provide good user feedback and you would actually know that it copied (in case it somehow fails).

**Comment by AiAe** [comment]
Implemented
