### ISSUE TITLE
A specific map doesn't have it's leaderboard loaded both ingame and on the website

### ISSUE THREAD

**Issue by Kizuna-dev** [Quaver/Quaver.Website#315]
https://quavergame.com/mapset/map/43987

For some reason this map doesn't show the leaderboard, even tho it's properly updated to the last version, as ingame it say "No Score available. be the first", as for proof that this map got played and is even shown on profile : 
![582021 14-20-50-490](https://user-images.githubusercontent.com/68703144/117539310-58265200-b00a-11eb-8365-84ad0a48cd19.jpg)
![582021 14-24-56-282](https://user-images.githubusercontent.com/68703144/117539318-5d839c80-b00a-11eb-8861-17b9631546e8.jpg)
![firefox_2qLw5kodN7](https://user-images.githubusercontent.com/68703144/117539336-7b510180-b00a-11eb-88cc-c9649a7a59ac.png)
^ this is on my profile on the first place page
it did also mention the first place on the profile activity, and also on the discord in the first-place channel

**Comment by AiAe** [comment]
Seems to be fixed now
