### ISSUE TITLE
Hidden button on profile page redirects to another player's profile

### ISSUE THREAD

**Issue by PuddyUK** [Quaver/Quaver.Website#320]
![image](https://user-images.githubusercontent.com/84622734/119223803-4efdb080-baf3-11eb-98ad-11d918c0ea10.png)
On my [player profile](https://quavergame.com/user/59782) there's a 22x29 invisible button next to the discord ID button that redirects to a player named "True" (https://quavergame.com/user/7276)

**Comment by AiAe** [comment]
Fixed
