### ISSUE TITLE
Plugin marketplace

### ISSUE THREAD

**Issue by Enn3Developer** [Quaver/Quaver.Website#330]
Add something like a marketplace for plugins so it's easier to know about them (so you don't have to surf github or asking on the discord) and it's easier to download, maybe even add the same marketplace to the client (like you do with maps, but I'm sure this part should go to the client side)

**Comment by Kubeon4** [comment]
or incorporate it into steam workshop :)

**Comment by AiAe** [comment]
Already added to workshop
