### ISSUE TITLE
Clans

### ISSUE THREAD

**Issue by Xylezia** [Quaver/Quaver.Website#346]
A lot of people (myself inclulded) have made clans via discord (examples include Act Broke Stay Rich, POL or QHK) that consist of a group of people who like playing the game together and sometimes  just having their own discord server. In terms of what they actually do, they're pretty lackluster. However, by actually implementing them in-game it would be a pretty good means of bringing the community together more, and an incentive for people to play the game more if clans had something like their own ranked leaderboards.

**How could this be implemented?**
Simple, have clans treated similar to players, where they all have their overall rating, their own leaderboards, and all their top scores (alternatively to encourage people to play together instead of top players just farming, have it so it's a few top plays from everyone in the group)

**Why should this be implemented?**
Right now, "clans" are nothing more than people just playing the game together, but by actually giving them meaning and a legitimate reason for them to exist, there will be more of an incentive for people to play together, and even an incentive for more people to come to the game so they can play with their friends

**Other possible ideas**
Clan-Exclusive things such as clan tags (could possibly be donator only so people don't try and workaround with their names), additionally, adding things such as searching song leaderboards by clan, and clan vs clan multiplayer lobbies. This could also be a good way of introducing group difficulties, although I'm not too familiar with mapping or a means on how that could be implemented.

**Comment by HanatachiMane** [comment]
i meeeeeeean

**Comment by BYE0L** [comment]
adding clans in game would be so good.

**Comment by Xylezia** [comment]
At the request of more gameplay-oriented/competitive features, here are some suggestions Act Broke Stay Rich have come up with:

A tag-team like gamemode where a map ranging between difficulties 10 and 20 is picked every few days. During the event, clans with a minimum of 3 members compete on the chosen map. Each clans score will be combined from the number of submitted plays and weighted, being treated in a similar manner to how an individual players scores are weighted. The clan with the highest overall QR will win after the allotted timeframe (IE 3-5 days.) The winner will be announced in a channel similar to the #first-places channel in game, and potential rewards may be granted to the winning clan. Afterwards, a new map will be selected and the event will repeat.

Similar to the first, an event where several maps (5 maybe?) are picked instead of a single map. The clan with the highest average leaderboard placements across all leaderboards will be the victor, and given rewards similar to the first event. This event allows a wider skillrange of players to compete, since a larger pool of maps ranging in varying difficulties can be chosen.

The maps could simply be determined by choosing ranked maps at random, or a list of pre-approved maps could come out and constantly be updated by RS. The maps could be announced using an in-game chat channel, or on the Quaver website (or both). As for rewards, a temporary profile badge on the website could be given out, which would be removed the next rotation. Additionally, the leaderboards for the second proposed idea should be temporary, to allow recycling of maps in the case that there are somehow not enough approved maps.

**Comment by flouncy301nanny** [comment]
the 8 people who disliked just dont have friends to be in a clan with

**Comment by 2-nil** [comment]
Very nice bestie

**Comment by nonameorous** [comment]
neat idea ig but i don't want to be bullied because of not being in a clan. 🤔

**Comment by flouncy301nanny** [comment]
> neat idea ig but i don't want to be bullied because of not being in a clan. 🤔

just be in a clan

**Comment by nonameorous** [comment]
that's the point, i don't want to 🙃
i think clans would add some sort of elitism to quaver. (like players who wouldn't be in clans would be considered "lame")

**Comment by flouncy301nanny** [comment]
> that's the point, i don't want to 🙃
> i think clans would add some sort of elitism to quaver. (like players who wouldn't be in clans would be considered "lame")

i don't think normal quaver players will do such thing and even if that was considered lame it would be a minority imo

**Comment by QiuFeng54321** [comment]
> i think clans would add some sort of elitism to quaver. (like players who wouldn't be in clans would be considered "lame")

people not in a clan is really not likely gonna call you "lame" since doing it would be calling themselves "lame" too xD
and people in a clan can invite you if you match their requirement and you would like to join them, otherwise i don't think they will even bring this up
even they say this you can always contact a chat mod tho
