### ISSUE TITLE
Website header font in homepage is not the same as the ones in the header of wiki page.

### ISSUE THREAD

**Issue by chirijidev** [Quaver/Quaver.Website#356]
Homepage:
![image](https://user-images.githubusercontent.com/55966752/134611424-a12290b9-422e-4f82-a217-8a06d1096301.png)

Wiki Page:
![image](https://user-images.githubusercontent.com/55966752/134611444-8ac5dd91-8a00-467d-9865-ee63ee0cef98.png)

You're welcome.

**Comment by AiAe** [comment]
Font is fixed, logo moves with few pixels and i'm not sure why lol
