### ISSUE TITLE
Some first place scores not shown after score recalc

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver.Website#399]
<img width="1107" alt="Screen Shot 2022-01-15 at 7 06 28 AM" src="https://user-images.githubusercontent.com/32996262/149596522-9290e329-00bd-43dd-b626-4b78bfaa7c66.png">
<img width="1124" alt="Screen Shot 2022-01-15 at 7 06 45 AM" src="https://user-images.githubusercontent.com/32996262/149596543-fa69961f-1e12-483c-93a3-251f11ad2473.png">
Before recalc first place gets thrown over by scores using new calc, removing the record from First Place tab.   
Then the score refreshes, becoming the first place again while the First Place tab won't add it back up.  
I don't know if it will be fixed when recalc finishes.

**Comment by Swan** [comment]
Will be fixed after the recalc completes
